# Ronin Ecosystem Tracker

In [12]:
from dune_client.client import DuneClient
import os
import joblib
import pandas as pd
from dotenv import load_dotenv
load_dotenv()


dune_api_key = os.getenv("DEFI_JOSH_DUNE_QUERY_API_KEY")

### _Fetching data for Top Game Contracts Overall Activity from https://dune.com/queries/5779698_

In [ ]:
dune = DuneClient(dune_api_key)
query_result = dune.get_latest_result(5779698)

rows = query_result.result.rows

data1 = pd.DataFrame(rows)

joblib.dump(data1, "../data/games_overall_activity.joblib")

['../data/games_overall_activity.joblib']

In [6]:
overall_df = joblib.load("../data/games_overall_activity.joblib")

overall_df

,avg_gas_price_in_gwei,game_project,total_volume_ron_sent_to_game,transaction_count,unique_players
0,24.971325,Pixels,167.028604,234593957,10825826
1,7.946293,Axie Infinity,160509.063792,193569800,8894989
2,18.361983,Lumiterra,1.860900,39662389,2325858
3,19.923089,Wild Forest,0.010100,24320562,888907
4,20.373741,The Machines Arena,0.000000,30578989,385842
5,19.966154,Apeiron,0.000000,33972270,305351
6,19.548229,Ragnarok: Monster World,58.259846,3269359,222607
7,20.000000,Fableborne,0.000000,7062393,110278
8,20.427206,Kongz,255195.704884,1121236,97199
9,20.871769,Pixel HeroZ,3210.715731,1418253,51965
10,21.567664,Fishing Frenzy,1.107159,1475394,43461
11,23.487094,Ronkeverse,192.000000,29007,20199
12,20.522718,Moki Genesis,0.000000,29165,14965
13,23.788180,Sabong Saga,50.400000,45748,10138
14,25.339320,Kaidro,0.000000,9442989,6241
15,23.884668,Cambria,479298.366133,226992,3970
16,25.764620,Mark of the Zeal,150.000000,3324,2147
17,25.125425,KttyWorld,27950.100000,97686,1945
18,25.476405,Planet Horse,75.000000,17586,1829
19,21.067423,Kojin Genesis,0.000000,739,328

### _Fetching data for Top Game Contracts Daily Activity from https://dune.com/queries/5781579_

In [7]:
dune2 = DuneClient(dune_api_key)
query_result2 = dune2.get_latest_result(5781579)

rows = query_result2.result.rows

data2 = pd.DataFrame(rows)

joblib.dump(data2, "../data/games_daily_activity.joblib")

['../data/games_daily_activity.joblib']

In [8]:
daily_df = joblib.load("../data/games_daily_activity.joblib")

daily_df

,avg_gas_price_in_gwei,day,game_project,total_volume_ron_sent_to_game,transaction_count,unique_players
0,27.613256,2025-09-07 00:00:00.000 UTC,Pixels,0.0,24363,23591
1,22.107143,2025-09-07 00:00:00.000 UTC,Sabong Saga,0.0,56,34
2,21.733171,2025-09-07 00:00:00.000 UTC,Ronkeverse,0.0,22,22
3,21.500000,2025-09-07 00:00:00.000 UTC,Mark of the Zeal,0.0,2,2
4,21.500000,2025-09-07 00:00:00.000 UTC,Moki Genesis,0.0,2,1
...,...,...,...,...,...,...
7703,0.592051,2021-05-02 00:00:00.000 UTC,Axie Infinity,0.0,9511,545
7704,0.559360,2021-05-01 00:00:00.000 UTC,Axie Infinity,0.0,9931,538
7705,0.456713,2021-04-30 00:00:00.000 UTC,Axie Infinity,0.0,11909,690
7706,0.557256,2021-04-29 00:00:00.000 UTC,Axie Infinity,0.0,11824,510
7707,0.654536,2021-04-28 00:00:00.000 UTC,Axie Infinity,0.0,3682,71

### _Fetching data for Daily Ronin Transactions, Active users/wallets, and Gas fees (GWEI) from https://dune.com/queries/5779439_

In [10]:
dune3 = DuneClient(dune_api_key)
query_result3 = dune3.get_latest_result(5779439)

rows = query_result3.result.rows

data3 = pd.DataFrame(rows)

joblib.dump(data3, "../data/ronin_daily_activity.joblib")

['../data/ronin_daily_activity.joblib']

In [11]:
ronin_daily_df = joblib.load("../data/ronin_daily_activity.joblib")

ronin_daily_df

,active_wallets,avg_gas_price_in_gwei,daily_transactions,day
0,234120,21.140833,498841,2025-09-07 00:00:00.000 UTC
1,285517,21.151198,730543,2025-09-06 00:00:00.000 UTC
2,288047,20.848433,661716,2025-09-05 00:00:00.000 UTC
3,283809,21.743497,694224,2025-09-04 00:00:00.000 UTC
4,284033,20.993838,905547,2025-09-03 00:00:00.000 UTC
...,...,...,...,...
1680,2,1.000000,2,2021-01-29 00:00:00.000 UTC
1681,1,1.000000,4,2021-01-28 00:00:00.000 UTC
1682,2,0.005634,355,2021-01-27 00:00:00.000 UTC
1683,5,0.000000,12,2021-01-26 00:00:00.000 UTC
1684,2,0.090909,11,2021-01-25 00:00:00.000 UTC